//! A small safe layer over libghostty-vt.
//!
//! The GUI keeps one [`Terminal`] per pane. Bytes from the tuios daemon go in
//! through [`Terminal::write`]; the painter reads rows back through
//! [`Terminal::snapshot_dirty`], which walks ghostty's render state and copies
//! only the rows ghostty marked dirty into plain Rust structs ([`Row`]). Those
//! structs carry resolved colours and flags, so the painter never calls into C.
//!
//! The raw bindings are in [`ffi`], generated by bindgen from the headers of
//! the ghostty commit tuios pins (see build.rs).

#![allow(clippy::missing_safety_doc)]

#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::all
)]
pub mod ffi;

mod snapshot;

pub use snapshot::{Cell, CellFlags, CursorShape, CursorState, Rgb, Row, Screen, UnderlineKind};

use ffi::*;
use std::ptr;

/// A pane emulator. Not `Send`: ghostty's handles are used from one thread.
pub struct Terminal {
    raw: GhosttyTerminal,
    render: GhosttyRenderState,
    rows: GhosttyRenderStateRowIterator,
    cells: GhosttyRenderStateRowCells,
    keys: GhosttyKeyEncoder,
    key_event: GhosttyKeyEvent,
    mouse: GhosttyMouseEncoder,
    mouse_event: GhosttyMouseEvent,
    cols: u16,
    rows_n: u16,
    /// The last copied screen. Rows are replaced as ghostty reports them dirty.
    screen: Screen,
    grapheme_buf: Vec<u32>,
    /// Where copy_row builds a row before it is swapped into place.
    scratch: Row,
    /// The row just above the viewport, for smooth scrolling: the viewport
    /// offset it was read at, and the row.
    above: Option<(u64, Row)>,
}

fn ok(r: GhosttyResult, what: &str) -> Result<(), String> {
    if r == GHOSTTY_SUCCESS {
        Ok(())
    } else {
        Err(format!("{what} failed: ghostty result {r}"))
    }
}

/// Packs a mode number the way the C header's inline `ghostty_mode_new` does.
pub const fn mode(value: u16, ansi: bool) -> GhosttyMode {
    (value & 0x7FFF) | ((ansi as u16) << 15)
}

pub const MODE_BRACKETED_PASTE: GhosttyMode = mode(2004, false);
pub const MODE_FOCUS_EVENT: GhosttyMode = mode(1004, false);
pub const MODE_ALT_SCROLL: GhosttyMode = mode(1007, false);
pub const MODE_DECCKM: GhosttyMode = mode(1, false);
pub const MODE_SYNC_OUTPUT: GhosttyMode = mode(2026, false);

/// Mouse tracking requested by the program in the pane.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MouseTracking {
    None,
    X10,
    Normal,
    Button,
    Any,
}

/// A key event in ghostty's terms, built by the GUI from its own key event.
#[derive(Debug, Clone, Default)]
pub struct KeyInput<'a> {
    /// A `GHOSTTY_KEY_*` value (physical key, US layout position).
    pub key: GhosttyKey,
    /// `GHOSTTY_MODS_*` bits.
    pub mods: u16,
    /// Mods the platform already used to produce `text` (usually shift).
    pub consumed_mods: u16,
    /// The text the key produces, if any.
    pub text: &'a str,
    /// The codepoint of the key without shift, for the kitty protocol.
    pub unshifted: u32,
    pub action: KeyAction,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum KeyAction {
    #[default]
    Press,
    Repeat,
    Release,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MouseAction {
    Press,
    Release,
    Motion,
}

/// Pixel geometry the mouse encoder needs to turn positions into cells.
#[derive(Debug, Clone, Copy)]
pub struct MouseGeometry {
    pub width: u32,
    pub height: u32,
    pub cell_width: u32,
    pub cell_height: u32,
}

impl Terminal {
    /// Creates an emulator of `cols` x `rows` with `scrollback` lines of history.
    pub fn new(cols: u16, rows: u16, scrollback: usize) -> Result<Self, String> {
        let cols = cols.max(1);
        let rows = rows.max(1);
        unsafe {
            let mut raw: GhosttyTerminal = ptr::null_mut();
            ok(ghostty_terminal_new(ptr::null(), &mut raw, cols, rows), "terminal_new")?;
            let lines: usize = scrollback;
            let _ = ghostty_terminal_set(
                raw,
                GHOSTTY_TERMINAL_OPT_SCROLLBACK_MAX_LINES,
                &lines as *const usize as *const _,
            );
            let mut render: GhosttyRenderState = ptr::null_mut();
            ok(ghostty_render_state_new(ptr::null(), &mut render), "render_state_new")?;
            let mut rows_it: GhosttyRenderStateRowIterator = ptr::null_mut();
            ok(
                ghostty_render_state_row_iterator_new(ptr::null(), &mut rows_it),
                "row_iterator_new",
            )?;
            let mut cells: GhosttyRenderStateRowCells = ptr::null_mut();
            ok(ghostty_render_state_row_cells_new(ptr::null(), &mut cells), "row_cells_new")?;
            let mut keys: GhosttyKeyEncoder = ptr::null_mut();
            ok(ghostty_key_encoder_new(ptr::null(), &mut keys), "key_encoder_new")?;
            let mut key_event: GhosttyKeyEvent = ptr::null_mut();
            ok(ghostty_key_event_new(ptr::null(), &mut key_event), "key_event_new")?;
            let mut mouse: GhosttyMouseEncoder = ptr::null_mut();
            ok(ghostty_mouse_encoder_new(ptr::null(), &mut mouse), "mouse_encoder_new")?;
            let mut mouse_event: GhosttyMouseEvent = ptr::null_mut();
            ok(ghostty_mouse_event_new(ptr::null(), &mut mouse_event), "mouse_event_new")?;
            Ok(Self {
                raw,
                render,
                rows: rows_it,
                cells,
                keys,
                key_event,
                mouse,
                mouse_event,
                cols,
                rows_n: rows,
                screen: Screen::blank(cols, rows),
                grapheme_buf: Vec::with_capacity(8),
                scratch: Row::default(),
                above: None,
            })
        }
    }

    pub fn cols(&self) -> u16 {
        self.cols
    }

    pub fn rows(&self) -> u16 {
        self.rows_n
    }

    /// Feeds PTY output. Replies to queries are dropped: the daemon's own
    /// emulator already answers them on the real PTY.
    pub fn write(&mut self, bytes: &[u8]) {
        if bytes.is_empty() {
            return;
        }
        self.above = None;
        unsafe { ghostty_terminal_vt_write(self.raw, bytes.as_ptr(), bytes.len()) }
    }

    pub fn resize(&mut self, cols: u16, rows: u16, cell_w: u32, cell_h: u32) {
        let cols = cols.max(1);
        let rows = rows.max(1);
        if cols == self.cols && rows == self.rows_n {
            return;
        }
        unsafe {
            let _ = ghostty_terminal_resize(self.raw, cols, rows, cell_w.max(1), cell_h.max(1));
        }
        self.cols = cols;
        self.rows_n = rows;
        self.screen = Screen::blank(cols, rows);
    }

    pub fn reset(&mut self) {
        unsafe { ghostty_terminal_reset(self.raw) }
    }

    /// Sets the default colours and the 256-colour palette (the theme).
    pub fn set_theme(&mut self, fg: Rgb, bg: Rgb, cursor: Rgb, palette: &[Rgb; 256]) {
        unsafe {
            let f = fg.into_ffi();
            let b = bg.into_ffi();
            let c = cursor.into_ffi();
            let _ = ghostty_terminal_set(self.raw, GHOSTTY_TERMINAL_OPT_COLOR_FOREGROUND, &f as *const _ as *const _);
            let _ = ghostty_terminal_set(self.raw, GHOSTTY_TERMINAL_OPT_COLOR_BACKGROUND, &b as *const _ as *const _);
            let _ = ghostty_terminal_set(self.raw, GHOSTTY_TERMINAL_OPT_COLOR_CURSOR, &c as *const _ as *const _);
            let pal: Vec<GhosttyColorRgb> = palette.iter().map(|c| c.into_ffi()).collect();
            let _ = ghostty_terminal_set(self.raw, GHOSTTY_TERMINAL_OPT_COLOR_PALETTE, pal.as_ptr() as *const _);
        }
        self.screen.full_dirty = true;
    }

    pub fn mode(&self, m: GhosttyMode) -> bool {
        let mut cfg = GhosttyTerminalModeConfig { mode: m, value: false };
        unsafe {
            if ghostty_terminal_get(self.raw, GHOSTTY_TERMINAL_DATA_MODE, &mut cfg as *mut _ as *mut _)
                != GHOSTTY_SUCCESS
            {
                return false;
            }
        }
        cfg.value
    }

    pub fn mouse_tracking(&self) -> MouseTracking {
        let mut v: GhosttyMouseTrackingMode = 0;
        unsafe {
            let _ = ghostty_terminal_get(self.raw, GHOSTTY_TERMINAL_DATA_MOUSE_TRACKING, &mut v as *mut _ as *mut _);
        }
        match v {
            GHOSTTY_MOUSE_TRACKING_X10 => MouseTracking::X10,
            GHOSTTY_MOUSE_TRACKING_NORMAL => MouseTracking::Normal,
            GHOSTTY_MOUSE_TRACKING_BUTTON => MouseTracking::Button,
            GHOSTTY_MOUSE_TRACKING_ANY => MouseTracking::Any,
            _ => MouseTracking::None,
        }
    }

    pub fn alt_screen(&self) -> bool {
        let mut v: GhosttyTerminalScreen = 0;
        unsafe {
            let _ = ghostty_terminal_get(self.raw, GHOSTTY_TERMINAL_DATA_ACTIVE_SCREEN, &mut v as *mut _ as *mut _);
        }
        v == GHOSTTY_TERMINAL_SCREEN_ALTERNATE
    }

    pub fn kitty_keyboard_flags(&self) -> u8 {
        let mut v: GhosttyKittyKeyFlags = 0;
        unsafe {
            let _ = ghostty_terminal_get(self.raw, GHOSTTY_TERMINAL_DATA_KITTY_KEYBOARD_FLAGS, &mut v as *mut _ as *mut _);
        }
        v
    }

    pub fn title(&self) -> String {
        self.get_string(GHOSTTY_TERMINAL_DATA_TITLE)
    }

    pub fn pwd(&self) -> String {
        self.get_string(GHOSTTY_TERMINAL_DATA_PWD)
    }

    fn get_string(&self, key: GhosttyTerminalData) -> String {
        let mut s = GhosttyString { ptr: ptr::null(), len: 0 };
        unsafe {
            if ghostty_terminal_get(self.raw, key, &mut s as *mut _ as *mut _) != GHOSTTY_SUCCESS
                || s.ptr.is_null()
            {
                return String::new();
            }
            String::from_utf8_lossy(std::slice::from_raw_parts(s.ptr, s.len)).into_owned()
        }
    }

    /// Scrollback position: (total rows, first visible row, visible rows).
    pub fn scrollbar(&self) -> (u64, u64, u64) {
        let mut sb = GhosttyTerminalScrollbar { total: 0, offset: 0, len: 0 };
        unsafe {
            let _ = ghostty_terminal_get(self.raw, GHOSTTY_TERMINAL_DATA_SCROLLBAR, &mut sb as *mut _ as *mut _);
        }
        (sb.total, sb.offset, sb.len)
    }

    /// Scrolls the viewport by `delta` rows (negative is up, into history).
    pub fn scroll_delta(&mut self, delta: isize) {
        if delta == 0 {
            return;
        }
        let b = GhosttyTerminalScrollViewport {
            tag: GHOSTTY_SCROLL_VIEWPORT_DELTA,
            value: GhosttyTerminalScrollViewportValue { delta },
        };
        unsafe { ghostty_terminal_scroll_viewport(self.raw, b) }
    }

    pub fn scroll_to_bottom(&mut self) {
        let b = GhosttyTerminalScrollViewport {
            tag: GHOSTTY_SCROLL_VIEWPORT_BOTTOM,
            value: GhosttyTerminalScrollViewportValue { delta: 0 },
        };
        unsafe { ghostty_terminal_scroll_viewport(self.raw, b) }
    }

    /// True when the viewport shows the live screen (not scrolled back).
    pub fn at_bottom(&self) -> bool {
        let (total, offset, len) = self.scrollbar();
        offset + len >= total
    }

    /// Encodes a key press for the program in the pane, honouring the
    /// cursor-key mode, keypad mode and the kitty keyboard flags it set.
    pub fn encode_key(&mut self, input: &KeyInput) -> Vec<u8> {
        unsafe {
            ghostty_key_encoder_setopt_from_terminal(self.keys, self.raw);
            let action = match input.action {
                KeyAction::Press => GHOSTTY_KEY_ACTION_PRESS,
                KeyAction::Repeat => GHOSTTY_KEY_ACTION_REPEAT,
                KeyAction::Release => GHOSTTY_KEY_ACTION_RELEASE,
            };
            ghostty_key_event_set_action(self.key_event, action);
            ghostty_key_event_set_key(self.key_event, input.key);
            ghostty_key_event_set_mods(self.key_event, input.mods);
            ghostty_key_event_set_consumed_mods(self.key_event, input.consumed_mods);
            ghostty_key_event_set_composing(self.key_event, false);
            ghostty_key_event_set_utf8(self.key_event, input.text.as_ptr() as *const _, input.text.len());
            ghostty_key_event_set_unshifted_codepoint(self.key_event, input.unshifted);
            let mut buf = [0u8; 128];
            let mut n = 0usize;
            let r = ghostty_key_encoder_encode(self.keys, self.key_event, buf.as_mut_ptr() as *mut _, buf.len(), &mut n);
            if r != GHOSTTY_SUCCESS {
                return Vec::new();
            }
            buf[..n].to_vec()
        }
    }

    /// Encodes a mouse event if the program asked for mouse reports.
    /// `x`/`y` are pixels from the pane's top-left corner.
    #[allow(clippy::too_many_arguments)]
    pub fn encode_mouse(
        &mut self,
        action: MouseAction,
        button: Option<u8>,
        mods: u16,
        x: f32,
        y: f32,
        geo: MouseGeometry,
        any_button_pressed: bool,
    ) -> Vec<u8> {
        unsafe {
            ghostty_mouse_encoder_setopt_from_terminal(self.mouse, self.raw);
            let size = GhosttyMouseEncoderSize {
                size: std::mem::size_of::<GhosttyMouseEncoderSize>(),
                screen_width: geo.width,
                screen_height: geo.height,
                cell_width: geo.cell_width.max(1),
                cell_height: geo.cell_height.max(1),
                padding_top: 0,
                padding_bottom: 0,
                padding_right: 0,
                padding_left: 0,
            };
            ghostty_mouse_encoder_setopt(self.mouse, GHOSTTY_MOUSE_ENCODER_OPT_SIZE, &size as *const _ as *const _);
            let pressed = any_button_pressed;
            ghostty_mouse_encoder_setopt(
                self.mouse,
                GHOSTTY_MOUSE_ENCODER_OPT_ANY_BUTTON_PRESSED,
                &pressed as *const bool as *const _,
            );
            let track = true;
            ghostty_mouse_encoder_setopt(
                self.mouse,
                GHOSTTY_MOUSE_ENCODER_OPT_TRACK_LAST_CELL,
                &track as *const bool as *const _,
            );
            ghostty_mouse_event_set_action(
                self.mouse_event,
                match action {
                    MouseAction::Press => GHOSTTY_MOUSE_ACTION_PRESS,
                    MouseAction::Release => GHOSTTY_MOUSE_ACTION_RELEASE,
                    MouseAction::Motion => GHOSTTY_MOUSE_ACTION_MOTION,
                },
            );
            match button {
                Some(b) => ghostty_mouse_event_set_button(self.mouse_event, b as GhosttyMouseButton),
                None => ghostty_mouse_event_clear_button(self.mouse_event),
            }
            ghostty_mouse_event_set_mods(self.mouse_event, mods);
            ghostty_mouse_event_set_position(self.mouse_event, GhosttyMousePosition { x, y });
            let mut buf = [0u8; 64];
            let mut n = 0usize;
            let r = ghostty_mouse_encoder_encode(self.mouse, self.mouse_event, buf.as_mut_ptr() as *mut _, buf.len(), &mut n);
            if r != GHOSTTY_SUCCESS {
                return Vec::new();
            }
            buf[..n].to_vec()
        }
    }

    /// Encodes pasted text: strips unsafe control bytes and wraps it in
    /// bracketed-paste markers when the program enabled mode 2004.
    pub fn encode_paste(&self, text: &str) -> Vec<u8> {
        let bracketed = self.mode(MODE_BRACKETED_PASTE);
        let mut data = text.as_bytes().to_vec();
        let mut out = vec![0u8; data.len() + 16];
        let mut n = 0usize;
        unsafe {
            let r = ghostty_paste_encode(
                data.as_mut_ptr() as *mut _,
                data.len(),
                bracketed,
                out.as_mut_ptr() as *mut _,
                out.len(),
                &mut n,
            );
            if r == GHOSTTY_OUT_OF_SPACE {
                out.resize(n, 0);
                let mut data = text.as_bytes().to_vec();
                let _ = ghostty_paste_encode(
                    data.as_mut_ptr() as *mut _,
                    data.len(),
                    bracketed,
                    out.as_mut_ptr() as *mut _,
                    out.len(),
                    &mut n,
                );
            } else if r != GHOSTTY_SUCCESS {
                return text.as_bytes().to_vec();
            }
        }
        out.truncate(n);
        out
    }

    fn viewport_ref(&self, x: u16, y: u16) -> Option<GhosttyGridRef> {
        let point = GhosttyPoint {
            tag: GHOSTTY_POINT_TAG_VIEWPORT,
            value: GhosttyPointValue { coordinate: GhosttyPointCoordinate { x, y: y as u32 } },
        };
        let mut r = GhosttyGridRef { size: std::mem::size_of::<GhosttyGridRef>(), node: ptr::null_mut(), x: 0, y: 0 };
        unsafe {
            if ghostty_terminal_grid_ref(self.raw, point, &mut r) != GHOSTTY_SUCCESS {
                return None;
            }
        }
        Some(r)
    }

    /// Selects from one viewport cell to another (inclusive). The terminal
    /// owns the selection, so it follows scrolling and shows up in snapshots.
    pub fn select(&mut self, start: (u16, u16), end: (u16, u16), rectangle: bool) {
        let clamp = |(x, y): (u16, u16)| (x.min(self.cols - 1), y.min(self.rows_n - 1));
        let (Some(a), Some(b)) = (self.viewport_ref(clamp(start).0, clamp(start).1), self.viewport_ref(clamp(end).0, clamp(end).1)) else {
            return;
        };
        let sel = GhosttySelection { size: std::mem::size_of::<GhosttySelection>(), start: a, end: b, rectangle };
        unsafe {
            let _ = ghostty_terminal_set(self.raw, GHOSTTY_TERMINAL_OPT_SELECTION, &sel as *const _ as *const _);
        }
        self.screen.full_dirty = true;
    }

    /// Selects the word under a viewport cell (double click).
    pub fn select_word(&mut self, x: u16, y: u16) {
        if let Some(r) = self.viewport_ref(x, y) {
            unsafe {
                let mut sel = GhosttySelection { size: std::mem::size_of::<GhosttySelection>(), start: r, end: r, rectangle: false };
                let opts = GhosttyTerminalSelectWordOptions { size: std::mem::size_of::<GhosttyTerminalSelectWordOptions>(), ref_: r, boundary_codepoints: ptr::null(), boundary_codepoints_len: 0 };
                if ghostty_terminal_select_word(self.raw, &opts, &mut sel) == GHOSTTY_SUCCESS {
                    let _ = ghostty_terminal_set(self.raw, GHOSTTY_TERMINAL_OPT_SELECTION, &sel as *const _ as *const _);
                }
            }
            self.screen.full_dirty = true;
        }
    }

    /// Selects the line under a viewport cell (triple click).
    pub fn select_line(&mut self, x: u16, y: u16) {
        if let Some(r) = self.viewport_ref(x, y) {
            unsafe {
                let mut sel = GhosttySelection { size: std::mem::size_of::<GhosttySelection>(), start: r, end: r, rectangle: false };
                let opts = GhosttyTerminalSelectLineOptions { size: std::mem::size_of::<GhosttyTerminalSelectLineOptions>(), ref_: r, whitespace: ptr::null(), whitespace_len: 0, semantic_prompt_boundary: false };
                if ghostty_terminal_select_line(self.raw, &opts, &mut sel) == GHOSTTY_SUCCESS {
                    let _ = ghostty_terminal_set(self.raw, GHOSTTY_TERMINAL_OPT_SELECTION, &sel as *const _ as *const _);
                }
            }
            self.screen.full_dirty = true;
        }
    }

    pub fn clear_selection(&mut self) {
        unsafe {
            let _ = ghostty_terminal_set(self.raw, GHOSTTY_TERMINAL_OPT_SELECTION, ptr::null());
        }
        self.screen.full_dirty = true;
    }

    /// The selected text as plain UTF-8, soft wraps joined, trailing spaces trimmed.
    pub fn selection_text(&self) -> Option<String> {
        let opts = GhosttyTerminalSelectionFormatOptions {
            size: std::mem::size_of::<GhosttyTerminalSelectionFormatOptions>(),
            emit: GHOSTTY_FORMATTER_FORMAT_PLAIN,
            unwrap: true,
            trim: true,
            selection: ptr::null(),
        };
        let mut p: *mut u8 = ptr::null_mut();
        let mut n = 0usize;
        unsafe {
            if ghostty_terminal_selection_format_alloc(self.raw, ptr::null(), opts, &mut p, &mut n) != GHOSTTY_SUCCESS {
                return None;
            }
            if p.is_null() {
                return Some(String::new());
            }
            let s = String::from_utf8_lossy(std::slice::from_raw_parts(p, n)).into_owned();
            ghostty_free(ptr::null(), p, n);
            Some(s)
        }
    }

    /// Copies dirty rows out of ghostty and returns the screen.
    ///
    /// Only rows ghostty reports dirty are rebuilt; each rebuilt row gets a new
    /// generation number so the painter can tell which rows to reshape.
    pub fn snapshot(&mut self) -> &Screen {
        unsafe { self.snapshot_inner() };
        &self.screen
    }

    pub fn screen(&self) -> &Screen {
        &self.screen
    }

    unsafe fn snapshot_inner(&mut self) {
        unsafe {
            if ghostty_render_state_update(self.render, self.raw) != GHOSTTY_SUCCESS {
                return;
            }
            let mut dirty: GhosttyRenderStateDirty = 0;
            let _ = ghostty_render_state_get(self.render, GHOSTTY_RENDER_STATE_DATA_DIRTY, &mut dirty as *mut _ as *mut _);
            let mut colors: GhosttyRenderStateColors = std::mem::zeroed();
            colors.size = std::mem::size_of::<GhosttyRenderStateColors>();
            let _ = ghostty_render_state_get(self.render, GHOSTTY_RENDER_STATE_DATA_COLORS, &mut colors as *mut _ as *mut _);
            let fg = Rgb::from_ffi(colors.foreground);
            let bg = Rgb::from_ffi(colors.background);
            let mut cur: GhosttyRenderStateCursor = std::mem::zeroed();
            cur.size = std::mem::size_of::<GhosttyRenderStateCursor>();
            let _ = ghostty_render_state_get(self.render, GHOSTTY_RENDER_STATE_DATA_CURSOR, &mut cur as *mut _ as *mut _);

            let full = dirty == GHOSTTY_RENDER_STATE_DIRTY_FULL
                || self.screen.full_dirty
                || fg != self.screen.fg
                || bg != self.screen.bg;
            if dirty == GHOSTTY_RENDER_STATE_DIRTY_FALSE && !full {
                self.update_cursor(&cur, &colors);
                return;
            }
            self.screen.fg = fg;
            self.screen.bg = bg;
            self.screen.full_dirty = false;
            let mut cols: u16 = 0;
            let mut rows: u16 = 0;
            let _ = ghostty_render_state_get(self.render, GHOSTTY_RENDER_STATE_DATA_COLS, &mut cols as *mut _ as *mut _);
            let _ = ghostty_render_state_get(self.render, GHOSTTY_RENDER_STATE_DATA_ROWS, &mut rows as *mut _ as *mut _);
            if cols != self.screen.cols || rows as usize != self.screen.rows.len() {
                self.screen = Screen::blank(cols, rows);
                self.screen.fg = fg;
                self.screen.bg = bg;
            }
            let mut it = self.rows;
            if ghostty_render_state_get(self.render, GHOSTTY_RENDER_STATE_DATA_ROW_ITERATOR, &mut it as *mut _ as *mut _)
                != GHOSTTY_SUCCESS
            {
                return;
            }
            let mut y: usize = 0;
            while ghostty_render_state_row_iterator_next(self.rows) {
                if y >= self.screen.rows.len() {
                    break;
                }
                let mut row_dirty = false;
                let _ = ghostty_render_state_row_get(self.rows, GHOSTTY_RENDER_STATE_ROW_DATA_DIRTY, &mut row_dirty as *mut _ as *mut _);
                if full || row_dirty {
                    self.copy_row(&colors);
                    std::mem::swap(&mut self.screen.rows[y], &mut self.scratch);
                    let off = false;
                    let _ = ghostty_render_state_row_set(self.rows, GHOSTTY_RENDER_STATE_ROW_OPTION_DIRTY, &off as *const bool as *const _);
                }
                y += 1;
            }
            let clean: GhosttyRenderStateDirty = GHOSTTY_RENDER_STATE_DIRTY_FALSE;
            let _ = ghostty_render_state_set(self.render, GHOSTTY_RENDER_STATE_OPTION_DIRTY, &clean as *const _ as *const _);
            self.update_cursor(&cur, &colors);
        }
    }

    /// The row just above the viewport, when the viewport is scrolled into
    /// history. Smooth scrolling shows part of it. Reading it moves the
    /// viewport up a row and back, so it is cached per viewport position.
    pub fn row_above(&mut self) -> Option<&Row> {
        let (_, offset, _) = self.scrollbar();
        if offset == 0 {
            return None;
        }
        if self.above.as_ref().is_none_or(|(o, _)| *o != offset) {
            self.scroll_delta(-1);
            let row = unsafe { self.read_first_row() };
            self.scroll_delta(1);
            self.screen.full_dirty = true;
            self.above = row.map(|r| (offset, r));
        }
        self.above.as_ref().map(|(_, r)| r)
    }

    unsafe fn read_first_row(&mut self) -> Option<Row> {
        unsafe {
            if ghostty_render_state_update(self.render, self.raw) != GHOSTTY_SUCCESS {
                return None;
            }
            let mut colors: GhosttyRenderStateColors = std::mem::zeroed();
            colors.size = std::mem::size_of::<GhosttyRenderStateColors>();
            let _ = ghostty_render_state_get(self.render, GHOSTTY_RENDER_STATE_DATA_COLORS, &mut colors as *mut _ as *mut _);
            let mut it = self.rows;
            if ghostty_render_state_get(self.render, GHOSTTY_RENDER_STATE_DATA_ROW_ITERATOR, &mut it as *mut _ as *mut _)
                != GHOSTTY_SUCCESS
                || !ghostty_render_state_row_iterator_next(self.rows)
            {
                return None;
            }
            self.copy_row(&colors);
            Some(self.scratch.clone())
        }
    }

    fn update_cursor(&mut self, cur: &GhosttyRenderStateCursor, colors: &GhosttyRenderStateColors) {
        self.screen.cursor = CursorState {
            visible: cur.visible && cur.viewport_has_value,
            x: cur.viewport_x,
            y: cur.viewport_y,
            wide: cur.wide_tail,
            blinking: cur.blinking,
            shape: match cur.visual_style {
                GHOSTTY_RENDER_STATE_CURSOR_VISUAL_STYLE_BAR => CursorShape::Bar,
                GHOSTTY_RENDER_STATE_CURSOR_VISUAL_STYLE_UNDERLINE => CursorShape::Underline,
                GHOSTTY_RENDER_STATE_CURSOR_VISUAL_STYLE_BLOCK_HOLLOW => CursorShape::Hollow,
                _ => CursorShape::Block,
            },
            color: colors.cursor_has_value.then(|| Rgb::from_ffi(colors.cursor)),
        };
    }

    unsafe fn copy_row(&mut self, colors: &GhosttyRenderStateColors) {
        unsafe {
            let mut cells = self.cells;
            if ghostty_render_state_row_get(self.rows, GHOSTTY_RENDER_STATE_ROW_DATA_CELLS, &mut cells as *mut _ as *mut _)
                != GHOSTTY_SUCCESS
            {
                return;
            }
            let mut raw_row: GhosttyRow = 0;
            let _ = ghostty_render_state_row_get(self.rows, GHOSTTY_RENDER_STATE_ROW_DATA_RAW, &mut raw_row as *mut _ as *mut _);
            let mut has_graphemes = false;
            let _ = ghostty_row_get(raw_row, GHOSTTY_ROW_DATA_GRAPHEME, &mut has_graphemes as *mut _ as *mut _);
            let mut wrapped = false;
            let _ = ghostty_row_get(raw_row, GHOSTTY_ROW_DATA_WRAP, &mut wrapped as *mut _ as *mut _);
            let mut sel = GhosttyRenderStateRowSelection { size: std::mem::size_of::<GhosttyRenderStateRowSelection>(), start_x: 0, end_x: 0 };
            let has_sel = ghostty_render_state_row_get(self.rows, GHOSTTY_RENDER_STATE_ROW_DATA_SELECTION, &mut sel as *mut _ as *mut _)
                == GHOSTTY_SUCCESS;

            let default_fg = Rgb::from_ffi(colors.foreground);
            let default_bg = Rgb::from_ffi(colors.background);
            let palette = &colors.palette;
            let generation = self.screen.next_generation();
            let row = &mut self.scratch;
            row.cells.clear();
            row.text.clear();
            row.wrapped = wrapped;
            let mut x: u16 = 0;
            while ghostty_render_state_row_cells_next(self.cells) {
                let mut raw: GhosttyCell = 0;
                let _ = ghostty_render_state_row_cells_get(self.cells, GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_RAW, &mut raw as *mut _ as *mut _);
                let mut wide: GhosttyCellWide = 0;
                let _ = ghostty_cell_get(raw, GHOSTTY_CELL_DATA_WIDE, &mut wide as *mut _ as *mut _);
                let mut has_text = false;
                let _ = ghostty_cell_get(raw, GHOSTTY_CELL_DATA_HAS_TEXT, &mut has_text as *mut _ as *mut _);
                let mut has_style = false;
                let _ = ghostty_cell_get(raw, GHOSTTY_CELL_DATA_HAS_STYLING, &mut has_style as *mut _ as *mut _);

                let mut flags = CellFlags::empty();
                let mut underline = UnderlineKind::None;
                let mut ul_color: Option<Rgb> = None;
                let mut style: GhosttyStyle = std::mem::zeroed();
                if has_style {
                    style.size = std::mem::size_of::<GhosttyStyle>();
                    let _ = ghostty_render_state_row_cells_get(self.cells, GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_STYLE, &mut style as *mut _ as *mut _);
                    if style.bold { flags |= CellFlags::BOLD; }
                    if style.italic { flags |= CellFlags::ITALIC; }
                    if style.faint { flags |= CellFlags::FAINT; }
                    if style.strikethrough { flags |= CellFlags::STRIKE; }
                    if style.overline { flags |= CellFlags::OVERLINE; }
                    if style.invisible { flags |= CellFlags::INVISIBLE; }
                    if style.blink { flags |= CellFlags::BLINK; }
                    underline = match style.underline {
                        GHOSTTY_SGR_UNDERLINE_SINGLE => UnderlineKind::Single,
                        GHOSTTY_SGR_UNDERLINE_DOUBLE => UnderlineKind::Double,
                        GHOSTTY_SGR_UNDERLINE_CURLY => UnderlineKind::Curly,
                        GHOSTTY_SGR_UNDERLINE_DOTTED => UnderlineKind::Dotted,
                        GHOSTTY_SGR_UNDERLINE_DASHED => UnderlineKind::Dashed,
                        _ => UnderlineKind::None,
                    };
                    ul_color = match style.underline_color.tag {
                        GHOSTTY_STYLE_COLOR_RGB => Some(Rgb::from_ffi(style.underline_color.value.rgb)),
                        GHOSTTY_STYLE_COLOR_PALETTE => Some(Rgb::from_ffi(palette[style.underline_color.value.palette as usize])),
                        _ => None,
                    };
                }
                let mut fgc = GhosttyColorRgb { r: 0, g: 0, b: 0 };
                let mut fg = if ghostty_render_state_row_cells_get(self.cells, GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_FG_COLOR, &mut fgc as *mut _ as *mut _)
                    == GHOSTTY_SUCCESS
                {
                    Rgb::from_ffi(fgc)
                } else {
                    default_fg
                };
                let mut bgc = GhosttyColorRgb { r: 0, g: 0, b: 0 };
                let mut bg = if ghostty_render_state_row_cells_get(self.cells, GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_BG_COLOR, &mut bgc as *mut _ as *mut _)
                    == GHOSTTY_SUCCESS
                {
                    Some(Rgb::from_ffi(bgc))
                } else {
                    None
                };
                // Bold text in one of the first 8 palette colours brightens, as
                // xterm and ghostty do by default.
                if has_style && style.bold && style.fg_color.tag == GHOSTTY_STYLE_COLOR_PALETTE {
                    let i = style.fg_color.value.palette as usize;
                    if i < 8 {
                        fg = Rgb::from_ffi(palette[i + 8]);
                    }
                }
                if has_style && style.inverse {
                    let new_fg = bg.unwrap_or(default_bg);
                    bg = Some(fg);
                    fg = new_fg;
                }
                if has_sel && x >= sel.start_x && x <= sel.end_x {
                    flags |= CellFlags::SELECTED;
                }
                match wide {
                    GHOSTTY_CELL_WIDE_WIDE => flags |= CellFlags::WIDE,
                    GHOSTTY_CELL_WIDE_SPACER_TAIL | GHOSTTY_CELL_WIDE_SPACER_HEAD => flags |= CellFlags::SPACER,
                    _ => {}
                }

                let start = row.text.len() as u32;
                if has_text && !flags.contains(CellFlags::SPACER) {
                    let mut cp: u32 = 0;
                    let _ = ghostty_cell_get(raw, GHOSTTY_CELL_DATA_CODEPOINT, &mut cp as *mut _ as *mut _);
                    if has_graphemes {
                        let mut n: u32 = 0;
                        let _ = ghostty_render_state_row_cells_get(self.cells, GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_GRAPHEMES_LEN, &mut n as *mut _ as *mut _);
                        if n > 1 {
                            self.grapheme_buf.clear();
                            self.grapheme_buf.resize(n as usize, 0);
                            let p = self.grapheme_buf.as_mut_ptr();
                            let _ = ghostty_render_state_row_cells_get(self.cells, GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_GRAPHEMES_BUF, p as *mut _);
                            for &c in &self.grapheme_buf {
                                if let Some(ch) = char::from_u32(c) {
                                    row.text.push(ch);
                                }
                            }
                        } else if let Some(ch) = char::from_u32(cp) {
                            row.text.push(ch);
                        }
                    } else if let Some(ch) = char::from_u32(cp) {
                        row.text.push(ch);
                    }
                }
                let len = (row.text.len() as u32 - start).min(255) as u8;
                row.cells.push(Cell { text_start: start, text_len: len, fg, bg, ul_color, flags, underline });
                x += 1;
            }
            row.generation = generation;
        }
    }
}

impl Drop for Terminal {
    fn drop(&mut self) {
        unsafe {
            ghostty_mouse_event_free(self.mouse_event);
            ghostty_mouse_encoder_free(self.mouse);
            ghostty_key_event_free(self.key_event);
            ghostty_key_encoder_free(self.keys);
            ghostty_render_state_row_cells_free(self.cells);
            ghostty_render_state_row_iterator_free(self.rows);
            ghostty_render_state_free(self.render);
            ghostty_terminal_free(self.raw);
        }
    }
}
